/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Elite.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.182, -0.165]} rotation={[-1.571, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body.geometry}
          material={materials.carpaint_metalic_blue}
          position={[0.001, 0.138, 0.547]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[0.001, 0.001, 0.001]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.black_windshield_mask.geometry}
            material={nodes.black_windshield_mask.material}
            position={[7.44, 105.325, -69.297]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.carpaintB_roof_pillars.geometry}
            material={nodes.carpaintB_roof_pillars.material}
            position={[0.632, 257.988, 319.242]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.chrome_lens_headlight.geometry}
            material={nodes.chrome_lens_headlight.material}
            position={[0.632, -139.589, -1342.461]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.chromeB_headlight.geometry}
            material={nodes.chromeB_headlight.material}
            position={[0.632, -1.802, -1866.712]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassClear_headlights_shell.geometry}
            material={nodes.glassClear_headlights_shell.material}
            position={[0.632, -62.203, -2032.607]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassClear_stoplight.geometry}
            material={nodes.glassClear_stoplight.material}
            position={[0.632, 228.414, -251.937]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassDark_windshield.geometry}
            material={nodes.glassDark_windshield.material}
            position={[0.632, 305.652, 414.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassLens_headlight.geometry}
            material={nodes.glassLens_headlight.material}
            position={[0.631, -86.769, -2018.036]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassRed_taillight.geometry}
            material={nodes.glassRed_taillight.material}
            position={[0.632, 87.273, 2000.458]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassRed_taillight_small.geometry}
            material={nodes.glassRed_taillight_small.material}
            position={[0.632, -211.2, 2024.445]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassRedIllum_taillight001.geometry}
            material={materials.glass_red_Illum}
            position={[0.632, 138.678, 1839.525]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.grey_sensor_windshield.geometry}
            material={nodes.grey_sensor_windshield.material}
            position={[151.606, 418.255, -424.482]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.metalDark_radiator.geometry}
            material={nodes.metalDark_radiator.material}
            position={[0.632, -312.266, -2135.913]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plastic_grill_inner.geometry}
            material={nodes.plastic_grill_inner.material}
            position={[-0.457, -114.856, -665.314]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plastic_headlight.geometry}
            material={materials.plasticblack}
            position={[0.632, -79.762, -2042.003]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plasticGlossy_headlight_lens_.geometry}
            material={nodes.plasticGlossy_headlight_lens_.material}
            position={[0.631, -189.643, -1857.513]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plasticGlossyB_undercarriage.geometry}
            material={nodes.plasticGlossyB_undercarriage.material}
            position={[0.632, -422.357, 714.23]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.reflect_headlight_lens.geometry}
            material={nodes.reflect_headlight_lens.material}
            position={[0.633, -152.995, 1267.627]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.silver_steering_wheel.geometry}
            material={nodes.silver_steering_wheel.material}
            position={[-317.768, 88.267, -395.365]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.glassBump_headlight_.geometry}
            material={materials.glass_bump}
            position={[0.631, -79.135, -2006.416]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.reflect_bump_headlight_led.geometry}
            material={materials.reflect_bump}
            position={[0.631, -79.227, -2011.835]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plasticBump_headlight_.geometry}
            material={materials.plasticblack_bump}
            position={[0.631, -103.287, -2033.377]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.texInterior_dashboard.geometry}
            material={materials.interior_tex}
            position={[-285.527, 82.288, -398.078]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plasticDots_bumper_r.geometry}
            material={materials.plastic_dots}
            position={[0.632, -360.389, 2019.438]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.interiorA_shell.geometry}
            material={materials.leather_black}
            position={[8.132, 132.406, 278.391]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.interiorB_.geometry}
            material={materials.leather_grey}
            position={[0.632, -48.693, -68.406]}
          />
        </mesh>
      </group>
      <group position={[0, 0, -1.574]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -2.78, 0.35]} rotation={[-Math.PI, 0, 0]}>
          <group position={[0, -2.78, 0]} rotation={[-Math.PI, 0, 0]}>
            <group position={[0, 0, -0.35]} rotation={[0, 0, 0]}>
              <group position={[0.806, -2.78, 0.35]}>
                <group position={[0.01, 0, 0]} />
                <group position={[0.226, 0, 0.175]} />
              </group>
              <group position={[-0.803, -2.78, 0.35]}>
                <group position={[-0.226, 0, 0.175]} />
              </group>
              <group position={[0.79, 0, 0.35]}>
                <group position={[0.012, 0, 0]} />
                <group position={[0.242, 0, 0.175]} />
              </group>
              <group position={[-0.786, 0, 0.35]}>
                <group position={[-0.242, 0, 0.175]} />
              </group>
              <group position={[0, -2.78, 0.35]} rotation={[0, 0, 0]}>
                <group position={[0, 0, 0]} rotation={[0, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -2.78, 0.35]} />
      </group>
      <group position={[0, 0.35, 1.207]} rotation={[-1.571, 0, 0]} />
      <group
        position={[0.84, 0.351, 1.206]}
        rotation={[-1.357, 0, Math.PI]}
        scale={[0.001, 0.001, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_1.geometry}
          material={materials.chrome_brushed_brakedisc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_2.geometry}
          material={materials['tire-car']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_3.geometry}
          material={materials.metal_rough}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_4.geometry}
          material={nodes.brakedisc_000002_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_5.geometry}
          material={materials.logo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_6.geometry}
          material={materials['Logo Top Material']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_7.geometry}
          material={materials['Logo Indent Material']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_8.geometry}
          material={materials['Logo Top Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brakedisc_000002_9.geometry}
          material={materials['Logo Indent Material.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Elite.gltf')
